accounts/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignUp.as_view(), name='signup'),

]

decision_helper/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls')),
    path('product/', include('products.urls')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('management/', include('management.urls')),
]

management/urls.py
from django.urls import path
from management import views

app_name = 'management'

urlpatterns = [
    ######################################################################################################
    path('departments/', views.DepartmentsListView.as_view(), name='departments_list'),
    path('departments/new/', views.DepartmentsCreateView.as_view(), name='departments_new'),
    path('departments/detail/<int:pk>/', views.DepartmentsDetailView.as_view(), name='departments_detail'),
    path('departments/update/<int:pk>/', views.DepartmentsUpdateView.as_view(), name='departments_update'),
    path('departments/delete/<int:pk>/', views.DepartmentsDeleteView.as_view(), name='departments_delete'),
    ##############################################################################################################3
    path('employees/', views.EmployeeListView.as_view(), name='employee_list'),
    path('employee/new/', views.EmployeeCreateView.as_view(), name='employee_new'),
    path('employee/detail/<int:pk>/', views.EmployeeDetailView.as_view(), name='employee_detail'),
    path('employee/update/<int:pk>/', views.EmployeeUpdateView.as_view(), name='employee_update'),
    path('employee/delete/<int:pk>/', views.EmployeeDeleteView.as_view(), name='employee_delete'),
    ##########################################################################################################
    path('salaries/', views.SalariesListView.as_view(), name='salaries_list'),
    path('salaries/new/', views.SalariesCreateView.as_view(), name='salaries_new'),
    path('salaries/detail/<int:pk>/', views.SalariesDetailView.as_view(), name='salaries_detail'),
    path('salaries/update/<int:pk>/', views.SalariesUpdateView.as_view(), name='salaries_update'),
    path('salaries/delete/<int:pk>/', views.SalariesDeleteView.as_view(), name='salaries_delete'),
    ##########################################################################################################
    path('titles/', views.TitlesListView.as_view(), name='titles_list'),
    path('titles/new/', views.TitlesCreateView.as_view(), name='titles_new'),
    path('titles/detail/<int:pk>/', views.TitlesDetailView.as_view(), name='titles_detail'),
    path('titles/update/<int:pk>/', views.TitlesUpdateView.as_view(), name='titles_update'),
    path('titles/delete/<int:pk>/', views.TitlesDeleteView.as_view(), name='titles_delete'),
    ##########################################################################################################
    path('deptmanager/', views.DeptManagerListView.as_view(), name='dept_manager_list'),
    path('deptmanager/new/', views.DeptManagerCreateView.as_view(), name='dept_manager_new'),
    path('deptmanager/detail/<int:pk>/', views.DeptManagerDetailView.as_view(), name='dept_manager_detail'),
    path('deptmanager/update/<int:pk>/', views.DeptManagerUpdateView.as_view(), name='dept_manager_update'),
    path('deptmanager/delete/<int:pk>/', views.DeptManagerDeleteView.as_view(), name='dept_manager_delete'),
    ##########################################################################################################
    path('deptemployee/', views.DeptEmployeeListView.as_view(), name='dept_employee_list'),
    path('deptemployee/new/', views.DeptEmployeeCreateView.as_view(), name='dept_employee_new'),
    path('deptemployee/detail/<int:pk>/', views.DeptEmployeeDetailView.as_view(), name='dept_employee_detail'),
    path('deptemployee/update/<int:pk>/', views.DeptEmployeeUpdateView.as_view(), name='dept_employee_update'),
    path('deptemployee/delete/<int:pk>/', views.DeptEmployeeDeleteView.as_view(), name='dept_employee_delete'),
    ##########################################################################################################
    
]

management/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Employee(models.Model):
    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
    )

    emp_no = models.AutoField(primary_key=True, null=False)
    birth_date = models.DateField(null=True)
    first_name = models.CharField(max_length=14)
    last_name = models.CharField(max_length=16) 
    gender = models.CharField(max_length=1, null=True, choices=GENDER_CHOICES)
    hire_date = models.DateField(null=True)

    class Meta:
        db_table = 'employees'
        ordering = ['hire_date']

    def __str__(self):
        return self.first_name + ' ' + self.last_name

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("management:employee_detail", kwargs={"pk": self.pk})

    def fullname(self):
        return self.first_name + ' ' + self.last_name


    #VSCode will see the objects declared
    objects = models.Manager()
    

class Departments(models.Model):
    dept_no = models.AutoField(primary_key=True, null=False)
    dept_name = models.CharField(unique=True, max_length=40)
 
    class Meta:
        db_table = 'departments'

    def __str__(self):
        return self.dept_name

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('management:departments_detail', kwargs={'pk': self.pk})

    #VSCode will see the objects declared
    objects = models.Manager()
    
class DeptEmployee(models.Model):
    emp_no = models.OneToOneField(Employee, on_delete=models.DO_NOTHING)
    dept_no = models.ForeignKey(Departments, on_delete=models.DO_NOTHING)
    from_date = models.DateField(null=True)
    to_date = models.DateField(null = True)

    class Meta:
        unique_together = (('emp_no', 'dept_no'),)
    def __str__(self):
        return self.emp_no + ' ' +self.dept_no
    
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('management:dept_employee_detail', kwargs={'pk': self.pk})

    #VSCode will see the objects declared
    objects = models.Manager()


class DeptManager(models.Model):
    dept_no = models.OneToOneField(Departments, on_delete=models.DO_NOTHING, db_column='dept_no')
    emp_no = models.ForeignKey(Employee, on_delete=models.DO_NOTHING, db_column='emp_no')
    from_date = models.DateField(null=True)
    to_date = models.DateField(null=True)

    class Meta:
        db_table = 'dept_manager'
        unique_together = (('emp_no', 'dept_no'),)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('management:dept_manager_detail', kwargs={'pk': self.pk})

    #VSCode will see the objects declared
    objects = models.Manager()
        

class Salaries(models.Model):
    emp_no = models.ForeignKey(Employee, related_name='salary', on_delete=models.DO_NOTHING, db_column='emp_no')
    amount = models.PositiveIntegerField(null=True)
    advance = models.PositiveIntegerField(null=True)
    from_date = models.DateField(null=True)
    to_date = models.DateField(null=True)

    class Meta:
        db_table = 'salaries'
        unique_together = (('emp_no', 'from_date'),)

    def __str__(self):
        return str(self.emp_no) +"'s salary from " +  str(self.from_date) + ' to '+ str(self.to_date)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('management:salaries_detail', kwargs={'pk': self.pk})

    #VSCode will see the objects declared
    objects = models.Manager()


class Titles(models.Model):
    emp_no = models.ForeignKey(Employee, related_name='title', on_delete=models.DO_NOTHING, db_column='emp_no')
    title = models.CharField(max_length=50)
    from_date = models.DateField(null=True)
    to_date = models.DateField(blank=True, null=True)

    class Meta:
        db_table = 'titles'
    
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('management:titles_detail', kwargs={'pk': self.pk})

    #VSCode will see the objects declared
    objects = models.Manager()

management/forms.py
from django import forms
from management.models import (Titles, Departments,
                             Employee, Salaries,
                             DeptEmployee, DeptManager)
from bootstrap_datepicker_plus import DatePickerInput
from bootstrap4_datetime.widgets    import DateTimePicker

class DepartmentsForm(forms.ModelForm):

    class Meta():
        model = Departments
        fields = ['dept_name']

class EmployeeForm(forms.ModelForm):

    class Meta():
        model=Employee
        fields = ['first_name', 'last_name', 'gender', 'birth_date', 'hire_date']
        widgets = {
            'birth_date':forms.DateInput(attrs={'type': 'date'}),
            'hire_date':forms.DateInput(attrs={'type': 'date'})
        }

class SalariesForm(forms.ModelForm):

    class Meta():
        model = Salaries
        exclude = ['advance']      
        widgets = {
            'from_date':forms.DateInput(attrs={'type': 'date'}),
            'to_date': forms.DateInput(attrs={'type': 'date'})
        }

class TitlesForm(forms.ModelForm):

    class Meta():
        model = Titles
        fields = '__all__'
        widgets = {
            'from_date':forms.DateInput(attrs={'type': 'date'}),
            'to_date': forms.DateInput(attrs={'type': 'date'})
        }

class DeptEmployeeForm(forms.ModelForm):

    class Meta():
        model = DeptEmployee
        fields = '__all__'
        widgets = {
            'from_date':forms.DateInput(attrs={'type': 'date'}),
            'to_date': forms.DateInput(attrs={'type': 'date'})
        }


class DeptManagerForm(forms.ModelForm):
    
    class Meta():
        model = DeptManager
        fields = '__all__'
        widgets = {
            'from_date':forms.DateInput(attrs={'type': 'date'}),
            'to_date': forms.DateInput(attrs={'type': 'date'})
        }

management/views.py
from django.shortcuts import render
from management.models import (Departments, Employee,
                                Salaries, Titles,
                                DeptEmployee, DeptManager)
from django.views.generic import (CreateView, DetailView,
                                    UpdateView, DeleteView,
                                    ListView )
from django.contrib.auth.mixins import LoginRequiredMixin
from management.forms import (DepartmentsForm, EmployeeForm,
                                SalariesForm, TitlesForm,
                                DeptEmployeeForm, DeptManagerForm)
from django.urls import reverse_lazy


# Create your views here.
###################################################################################

#Department Views

class DepartmentsCreateView(LoginRequiredMixin, CreateView):
    model = Departments
    login_url = '/login/'
    # redirect_field_name = 'management/department_detail.html'
    form_class = DepartmentsForm

class DepartmentsDetailView(LoginRequiredMixin, DetailView):
    model = Departments

class DepartmentsUpdateView(LoginRequiredMixin, UpdateView):
    model = Departments
    login_url = '/login/'
    form_class = DepartmentsForm
    template_name_suffix = '_update_form'


class DepartmentsDeleteView(LoginRequiredMixin, DeleteView):
    model = Departments
    success_url = reverse_lazy('management:departments_list')

class DepartmentsListView(ListView):
    model = Departments

#DeptManager views 

class DeptManagerCreateView(LoginRequiredMixin, CreateView):
    model = DeptManager
    form_class = DeptManagerForm

class DeptManagerDetailView(LoginRequiredMixin, DetailView):
    model = DeptManager

class DeptManagerUpdateView(LoginRequiredMixin, UpdateView):
    model = DeptManager
    form_class = DeptManagerForm
    template_name_suffix = '_update_form'

class DeptManagerDeleteView(LoginRequiredMixin, DeleteView):
    model = DeptManager
    success_url = reverse_lazy('management: deptmanager_list')

class DeptManagerListView(LoginRequiredMixin, ListView):
    model = DeptManager

#DeptEmployee views

class DeptEmployeeCreateView(LoginRequiredMixin, CreateView):
    model = DeptEmployee
    form_class = DeptEmployeeForm

class DeptEmployeeDetailView(LoginRequiredMixin, DetailView):
    model = DeptEmployee

class DeptEmployeeUpdateView(LoginRequiredMixin, UpdateView):
    model = DeptEmployee
    form_class = DeptEmployeeForm

class DeptEmployeeDeleteView(LoginRequiredMixin, DeleteView):
    model = DeptEmployee
    success_url = reverse_lazy('management: deptemployee_list')

class DeptEmployeeListView(LoginRequiredMixin, ListView):
    model = DeptEmployee


##############################################################################
#Employee views
class EmployeeCreateView(LoginRequiredMixin, CreateView):
    model = Employee
    form_class = EmployeeForm

class EmployeeDetailView(LoginRequiredMixin, DetailView):
    model = Employee

class EmployeeUpdateView(LoginRequiredMixin, UpdateView):
    model = Employee
    form_class = EmployeeForm
    template_name_suffix = '_update_form'


class EmployeeDeleteView(LoginRequiredMixin, DeleteView):
    model = Employee
    success_url = reverse_lazy('management:employee_list')

class EmployeeListView(LoginRequiredMixin, ListView):
    model = Employee

#######################################################################################

class SalariesCreateView(LoginRequiredMixin, CreateView):
    model = Salaries
    form_class = SalariesForm

class SalariesDetailView(LoginRequiredMixin, DetailView):
    model = Salaries

class SalariesUpdateView(LoginRequiredMixin, UpdateView):
    model = Salaries
    form_class = SalariesForm
    template_name_suffix = '_update_form'

class SalariesDeleteView(LoginRequiredMixin, DeleteView):
    model = Salaries
    success_url = reverse_lazy('management:salaries_list')

class SalariesListView(LoginRequiredMixin, ListView):
    model = Salaries

##########################################################################################

class TitlesCreateView(LoginRequiredMixin, CreateView):
    model = Titles
    form_class = TitlesForm

class TitlesDetailView(LoginRequiredMixin, DetailView):
    model = Titles

class TitlesUpdateView(LoginRequiredMixin, UpdateView):
    model = Titles
    form_class = TitlesForm
    template_name_suffix = '_update_form'

class TitlesDeleteView(LoginRequiredMixin, DeleteView):
    model = Titles
    success_url = reverse_lazy('management:titles_list')

class TitlesListView(LoginRequiredMixin, ListView):
    model = Titles

management/templates/management/confirm_delete_form.html
{% extends "base.html" %}
{% block content %}
  <form method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete {{object}}?</p>
    <input type="submit" class="btn btn-danger" name="" value="Confirm">
  </form>
{% endblock content %}

management/templates/management/departments_list.html
{% extends "base.html" %}
{% block content %}


<div class="container">
    <h2>Departments</h2>
    <ul class="list-group">
    {% for department in departments_list %}
        <li class="list-group-item"><a href = "{% url 'management:departments_detail' pk=department.pk %}">{{department.dept_name}}</a></li>
        
    {% endfor %}

</div>

{% endblock content %}

management/templates/management/departments_update_form.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block content %}

<div class="container">
  <h1>Update department</h1>
  <form method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" class="btn btn-default" value="Update Department">
  </form>
</div>

{% endblock content %}

management/templates/management/deptemployee_detail.html
{% extends "base.html" %}
{% block content %}

<h3>Name {{deptemployee.emp_no}} </h3>
<p> Department : {{deptemployee.dept_no}}</p>
<p> From: {{deptemployee.from_date}} </p>
<p> To: {{deptemployee.to_date}} </p>

{% if user.is_authenticated %}
  <a class='btn btn-secondary' href="{% url 'management:deptemployee_update' pk=deptemployee.pk %}">
    <span class='fas fa-pen'></span>
    <span class="text-body icon-label">Edit</span>
  </a>
  <a class='btn btn-secondary' href="{% url 'management:deptemployee_delete' pk=deptemployee.pk %}">
    <i class="fas fa-trash"></i>
    <span class="text-body icon-label">Delete</span>

  </a>
{% endif %}

{% endblock content %}

management/templates/management/deptemployee_form.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block content %}

<div class="container">
  <h1>Add Employee to department</h1>
  <form method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" class="btn btn-default" value="Add new employee to department">
  </form>
</div>

{% endblock content %}

management/templates/management/deptemployee_update_form.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block content %}

<div class="container">
  <h1>Update Employee's Department</h1>
  <form method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" class="btn btn-default" value="Update Employee Department">
  </form>
</div>

{% endblock content %}

management/templates/management/deptmanager_confirm_delete.html
{% extends "base.html" %}
{% block content %}
  <form method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete {{object}}?</p>
    <input type="submit" class="btn btn-danger" name="" value="Confirm">
  </form>
{% endblock content %}

management/templates/management/deptmanager_list.html
{% extends "base.html" %}
{% block content %}


<div class="container">
    <h2>Managers</h2>

        <table class="table">
            <thead class="thead-light">
                <tr>
                    <th>Department</th>
                    <th>Manager</th>
                    <th>From</th>
                    <th>To</th>
                </tr>
            </thead>
    {% for manager in deptmanager_list %}
            <tbody>
                <tr>
                    <td><a href = "{% url 'management:deptmanager_detail' pk=manager.pk %}">{{manager.dept_no}}</a></td>
                    <td>{{manager.emp_no}}</td>
                    <td>{{manager.from_date}}</td>
                    <td>{{manager.to_date}}</td>

                </tr>
            </tbody>

    {% endfor%}
        </table>
</div>

{% endblock content %}

management/templates/management/employee_detail.html
{% extends "base.html" %}
{% block content %}

<h3>Name {{employee.fullname}} </h3>
<p> Gender : {{employee.gender}}</p>
<p> DOB: {{employee.birth_date}} </p>
<p> Hired on: {{employee.hire_date}} </p>
<p> Title: 
  {% for title in employee.title.all %}

   {{title.title}},
  
  {% endfor %}
</p>


{% if user.is_authenticated %}
  <a class='btn btn-secondary' href="{% url 'management:employee_update' pk=employee.pk %}">
    <span class='fas fa-pen'></span>
    <span class="text-body icon-label">Edit</span>
  </a>
  <a class='btn btn-secondary' href="{% url 'management:employee_delete' pk=employee.pk %}">
    <i class="fas fa-trash"></i>
    <span class="text-body icon-label">Delete</span>

  </a>
{% endif %}

{% endblock content %}

management/templates/management/employee_list.html
{% extends "base.html" %}
{% block content %}


<div class="container">
    <h2>Employees</h2>

        <table class="table">
            <thead class="thead-light">
                <tr>
                    <th>Name</th>
                    <th>Gender</th>
                    <th>Date of Birth</th>
                    <th>Hired on</th>
                </tr>
            </thead>
    {% for employee in employee_list %}
            <tbody>
                <tr>
                    <td><a href = "{% url 'management:employee_detail' pk=employee.pk %}">{{employee.fullname}}</a></td>
                    <td>{{employee.gender}}</td>
                    <td>{{employee.birth_date}}</td>
                    <td>{{employee.hire_date}}</td>

                </tr>
            </tbody>

    {% endfor%}
        </table>
</div>

{% endblock content %}

management/templates/management/employee_update_form.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block content %}

<div class="container">
  <h1>Update Employee</h1>
  <form method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" class="btn btn-default" value="Update Employee">
  </form>
</div>

{% endblock content %}

management/templates/management/salaries_update_form.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block content %}

<div class="container">
  <h1>Update Salary</h1>
  <form method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" class="btn btn-default" value="Update Salary">
  </form>
</div>

{% endblock content %}

management/templates/management/titles_confirm_delete.html
{% extends "base.html" %}
{% block content %}
  <form method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete {{object}}?</p>
    <input type="submit" class="btn btn-danger" name="" value="Confirm">
  </form>
{% endblock content %}

management/templates/management/titles_detail.html
{% extends "base.html" %}
{% block content %}

<h3> {{titles.title}} : {{titles.emp_no}} </h3>
<p> From: {{titles.from_date}}</p>
<p> To: {{titles.to_date}}</p>


{% if user.is_authenticated %}
  <a class='btn btn-secondary' href="{% url 'management:titles_update' pk=titles.pk %}">
    <span class='fas fa-pen'></span>
    <span class="text-body icon-label">Edit</span>
  </a>
  <a class='btn btn-secondary' href="{% url 'management:titles_delete' pk=titles.pk %}">
    <i class="fas fa-trash"></i>
    <span class="text-body icon-label">Delete</span>

  </a>

{% endif %}

{% endblock content %}