accounts/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignUp.as_view(), name='signup'),

]

decision_helper/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls')),
    path('product/', include('products.urls')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('management/', include('management.urls')),
]

products/urls.py
from django.urls import path
from products import views

app_name='products'
urlpatterns = [
    path('new/', views.CreateProductView.as_view(), name='product_new'),
    path('detail/<int:pk>/', views.ProductDetailView.as_view(), name='product_detail'),
    path('', views.ProductListView.as_view(), name='product_list'),
    path('update/<int:pk>/', views.ProductUpdateView.as_view(), name='product_update'),
    path('delete/<int:pk>/', views.ProductDeleteView.as_view(), name='product_delete'),

]

products/models.py
from django.db import models
from django.utils.text import slugify
from django.urls import reverse

# Create your models here.
import misaka

class Product(models.Model):
    #VSCode will see the objects declared
    objects = models.Manager()

    name = models.CharField(max_length=255, unique=True)
    price = models.PositiveIntegerField()	
    quantity = models.PositiveIntegerField()
    

    def __str__(self):
        return self.name
    
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('products:product_detail', kwargs={'pk':self.pk})

    class Meta:
        ordering = ['name']

products/forms.py
from django import forms
from products.models import Product

class ProductForm(forms.ModelForm):

    class Meta():
        model = Product
        fields = ('name', 'price', 'quantity')

products/views.py
from products.forms import ProductForm
from products.models import Product
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, DeleteView, ListView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required

# Create your views here.
class CreateProductView(LoginRequiredMixin, CreateView):
    login_url = '/login/'
    redirect_field_name = 'product/product_detail.html'
    form_class = ProductForm
    model = Product

class ProductUpdateView(LoginRequiredMixin, UpdateView):
    login_url = '/login/'
    redirect_field_name = 'products/product_detail.html'
    template_name_suffix = '_update_form'
    form_class = ProductForm
    model = Product



class ProductDetailView(DetailView):
    model = Product

class ProductListView(ListView):
    model = Product

    def get_queryset(self):
        return Product.objects.order_by('name')

class ProductDeleteView(LoginRequiredMixin, DeleteView):
    login_url = '/login/'
    model = Product
    success_url = reverse_lazy('products:product_list')

products/templates/products/product_confirm_delete.html
{% extends "base.html" %}
{% block content %}
  <form method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete {{object}}?</p>
    <input type="submit" class="btn btn-danger" name="" value="Confirm">
  </form>
{% endblock content %}

products/templates/products/product_detail.html
{% extends "base.html" %}
{% block content %}

<h3> {{product.name}} </h3>
<p> Price: {{product.price}}</p>
<p> In Stock: {{product.quantity}}

{% if user.is_authenticated %}
  <a class='btn btn-secondary' href="{% url 'products:product_update' pk=product.pk %}">
    <span class='fas fa-pen'></span>
    <span class="text-body icon-label">Edit</span>
  </a>
  <a class='btn btn-secondary' href="{% url 'products:product_delete' pk=product.pk %}">
    <i class="fas fa-trash"></i>
    <span class="text-body icon-label">Delete</span>

  </a>
{% endif %}

{% endblock content %}

products/templates/products/product_form.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block content %}

<div class="container">
  <h1>Add new product</h1>
  <form method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" class="btn btn-default" value="New product">
  </form>
</div>

{% endblock content %}

products/templates/products/product_list.html
{% extends "base.html" %}
{% block content %}


<div class="container">
    <h2>Products</h2>

        <table class="table">
            <thead class="thead-dark">
                <tr>
                    <th>Name</th>
                    <th>Price</th>
                    <th>Quantity</th>
                </tr>
            </thead>
    {% for product in product_list %}
            <tbody>
                <tr>
                    <td><a href = "{% url 'products:product_detail' pk=product.pk %}">{{product.name}}</a></td>
                    <td>{{product.price}}</td>
                    <td>{{product.quantity}}</td>
                </tr>
            </tbody>

    {% endfor%}
        </table>
</div>

{% endblock content %}

products/templates/products/product_update_form.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block content %}

<div class="container">
  <h1>Update product</h1>
  <form method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" class="btn btn-default" value="Update Product">
  </form>
</div>

{% endblock content %}